name: Deploy Bicep files

trigger:
- none

variables:
  resourceGroupName: 'DEMO-RG'
  location: 'eastus'
  templateFile: './deployment.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: Preview Bicep Changes
  inputs:
    azureSubscription: 'Free Trial (3b56a1ce-9761-4c72-9968-48d7d873705c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az upgrade
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group what-if --resource-group $(resourceGroupName) \
         --template-file $(templateFile) 

- task: AzureCLI@2
  displayName: Validate Bicep To Azure
  inputs:
    azureSubscription: 'Free Trial (3b56a1ce-9761-4c72-9968-48d7d873705c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate --resource-group $(resourceGroupName) \
         --template-file $(templateFile)

- task: AzureCLI@2
  displayName: Deploy Bicep To Azure
  inputs:
    azureSubscription: 'Free Trial (3b56a1ce-9761-4c72-9968-48d7d873705c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) \
         --template-file $(templateFile)
